### ISSUE TITLE
Add footer and menu to every page

### ISSUE THREAD

**Issue by limo1996** [limo1996/WebTech#8]
Guys please add footer and menu from index.html to pages created by you.. Thx

**Comment by limo1996** [comment]
Tomas pridaj skripty na koniec filu co si teraz upravoval, tie co su v index.html na koci fileu..

**Comment by thomas16mr** [comment]
OK

Dňa 9.12.2016 11:51 používateľ "Jakub Lichman" <notifications@github.com>
napísal:

**Comment by permmo** [comment]
Pridane na stranku Meniny.
